# Generated by Django 5.1 on 2024-08-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_pickup', models.CharField(max_length=255)),
                ('folder_send', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
